# Login Details
valid_email = ''
password = ''

# Add Centre Name
centre_name = '_QAAutoTestCentre1'

# Add new people
first_name = 'Test'
last_name = 'Tester4'
people_email = ''
people_password = ''
people_confirm_password = ''

# Clone Centre name
cloned_centre_name = '_QA AutoCloned Centre'
cloned_centre_name_2 = '_QA AutoCloned Centre 2'

# Add CMS User
cms_user_firstname = 'Test1'
cms_user_lastname = 'Tester1'
cms_user_email = ''

# New ticket
ticket_title = 'QA Ticket AutoTest'
company = 'QA'
ticket_creator_name = 'Joe Bloggs'
ticket_details = 'Testing'
place_of_work = "QA Dept"

# New Item
item_title = "QA Item 1"

# Templates
template_name = "QA Template Test"
template_display_name = "QA Template Test"
template_data = "This is a template test."

# Create New Button
button_name = 'QA AutoTest Button'

# Virtual Onboarding
vo_first_name = 'QA3'
vo_last_name = 'QATester3'
vo_email_address = ''


# Ticket Response
response_order = 1
response_title = 'QA Auto Test'
response_text = 'This is generated by test automation'
comment_1 = 'Permission Test'
comment_2 = 'This is for auto test'
comment_3 = 'QA'


# CRM Add new contact
crm_name = 'Tester1'

# MallcommMail
mm_subject = 'QA Test'
mm_message = 'This is an automated Mallcomm Mail test'

# Access Level
access_level_name = 'QA Member'

# CMS New Role
cms_new_role_name = 'Visitor'

# Centre tags
tag = "QA Auto Tag"
display_label = "QA Auto Tag Label"



