# Login Details
valid_email = 'chidozie.amefule@toolboxmarketing.com'
password = 'Jayjay@okocha10'

# Add Centre Name
centre_name = 'QAAutoTestCentre1'

# Add new people
first_name = 'Test'
last_name = 'Tester4'
people_email = 'chidozie.amefule+110@toolboxmarketing.com'
people_password = 'Password01!'
people_confirm_password = 'Password01!'

# Clone Centre name
cloned_centre_name = 'QA AutoCloned Centre'
cloned_centre_name_2 = 'QA AutoCloned Centre 2'

# Add CMS User
cms_user_firstname = 'Test1'
cms_user_lastname = 'Tester1'
cms_user_email = 'chidozie.amefule+201@toolboxmarketing.com'

# New ticket
ticket_title = 'QA Ticket AutoTest'
company = 'QA'
ticket_creator_name = 'Joe Bloggs'
ticket_details = 'Testing'
place_of_work = "QA Dept"

# New Item
item_title = "QA Item 1"

# Templates
template_name = "QA Template Test"
template_display_name = "QA Template Test"
template_data = "This is a template test."

# Create New Button
button_name = 'QA AutoTest Button'

# Virtual Onboarding
vo_first_name = 'QA3'
vo_last_name = 'QATester3'
vo_email_address = 'chidozie.amefule+301@toolboxmarketing.com'


# Ticket Response
response_order = 1
response_title = 'QA Auto Test'
response_text = 'This is generated by test automation'